import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  about,
  contact,
}: Readonly<{
  children: React.ReactNode;
  about: React.ReactNode;
  contact: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav className="flex items-center justify-between p-10 bg-black  text-white">
            <div className="text-2xl font-bold">
              <Link href="/">My Next.js App</Link>
            </div>
            <ul className="flex space-x-4 ">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li> 
                <Link href="/book">book</Link>
              </li>
              <li>
                <Link href="/dashboard">dashboard</Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
        {about}
        {contact}
        <footer>
          <div className="p-10 bg-black text-white text-center">
            &copy; 2024 My Next.js App. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
