-- Q6: Find the most popular product by the total quantity sold.

SELECT
p.ProductID,
p.ProductName,
SUM(o.Quantity) as Total_Quantity
FROM orderdetails o
INNER JOIN product p on p.ProductID=o.ProductID
GROUP BY p.ProductID
ORDER BY Total_Quantity DESC
LIMIT 1;


-- Q7: Find the total revenue generated by each customer.

SELECT
c.CustomerId,
CONCAT(c.FirstName,' ',c.LastName) AS Name,
SUM(p.price*od.quantity) AS Total_Revenue
FROM Customer c
INNER JOIN Orders o ON c.CustomerId=o.CustomerId
INNER JOIN OrderDetails od ON o.OrderID=od.OrderID
INNER JOIN Product p ON od.ProductId=p.ProductId
GROUP BY c.CustomerId,Name;

-- q8 -Find all products that are out of stock.
SELECT ProductID,ProductName,Stock FROM product where stock=0;


-- Q9: List customers who placed orders in the last 30 days.
SELECT
c.CustomerId,
CONCAT(c.FirstName,' ',c.LastName) AS Name,
o.OrderDate
FROM Customer c
INNER JOIN Orders o on o.CustomerId=c.CustomerId
WHERE o.OrderDate>=CURDATE()-INTERVAL 30 DAY;
-- Current date minus 2 day => 3 days before current date
select CURDATE()-INTERVAL 2 DAY;

-- Q10: Retrieve the average order amount.
SELECT SUM(TotalAmount)/COUNT(OrderID) Average_Order_amount FROM orders o;
SELECT AVG(TotalAmount)Average_Order_amount FROM orders o;
